global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - scheme: http
      timeout: 10s
      api_version: v1
      static_configs:
        - targets: []
scrape_configs:
  - job_name: dotnet application
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - host.docker.internal:8080
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node-exporter
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']  
          # - host.docker.internal:9090
  # - job_name: prometheus
  #   static_configs:
  #     - targets:
  #         - localhost:9090
  # - job_name: grafana
  #   static_configs:
  #     - targets:
  #         - localhost:3000
  # - job_name: dotnet core
  #   static_configs:
  #     - targets:
  #         - localhost:7152
