version: '3'
services:
   nginx:
      image: nginx:latest
      container_name: nginx-container
      ports:
         - '80:80'
      volumes:
          - ./nginx:/etc/nginx/nginx.conf
   
   dev_app:
      image: shafikur/aspdotnet-app:dev
      container_name: dev_app-container
      ports:
         - '8081:8080'
   
   prod_app:
      image: shafikur/aspdotnet-app:prod
      container_name: prod_app-container
      ports:
         - '8082:8080'