version: '3'
services:
   # lazydocker:
   #    build:
   #       context: https://github.com/jesseduffield/lazydocker.git
   #       args:
   #          BASE_IMAGE_BUILDER: golang
   #          GOARCH: amd64
   #          GOARM:
   #    image: lazyteam/lazydocker
   #    container_name: lazydocker
   #    stdin_open: true
   #    tty: true
   #    volumes:
   #       - /var/run/docker.sock:/var/run/docker.sock
   #       - ./config:/.config/jesseduffield/lazydocker

   # postgresql:
   #    image: postgres:latest
   #    container_name: postgresql-container
   #    environment:
   #       POSTGRES_DB: my_database
   #       POSTGRES_USER: my_user
   #       POSTGRES_PASSWORD: 12345
   #    ports:
   #       - '5432:5432'
   #    volumes:
   #       - ./local_pgdata:/var/lib/postgresql/data

   # cassandra:
   #    image: cassandra:5.0
   #    container_name: cassandra-container
   #    ports:
   #       - '9042:9042'
   #    environment:
   #       - CASSANDRA_USER=admin
   #       - CASSANDRA_PASSWORD=admin
   #    volumes:
   #       - ./cassandra:/var/lib/cassandra
   #       - ./cassandra-logs:/var/log/cassandra

   # redis:
   #    image: redis:latest
   #    container_name: redis-container
   #    ports:
   #       - '6379:6379'
   #    environment:
   #       - REDIS_LOG_LEVEL=notic

   # nginx:
   #    image: nginx:latest
   #    container_name: nginx-container
   #    ports:
   #       - '80:80'
   
   
   # zookeeper
   zookeeper:
      image: docker.io/bitnami/zookeeper:3.9
      container_name: zookeeper-container   
      ports:
         - '2182:2181'
      environment:
         - ALLOW_ANONYMOUS_LOGIN=yes

   # kafka 
   kafka:
      image: docker.io/bitnami/kafka:3.4
      container_name: kafka-container
      ports:
         - '9093:9092'
      environment:
         - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      depends_on:
         - zookeeper
   
   # kafka-ui
   kafka-ui:
      image: provectuslabs/kafka-ui:latest
      container_name: kafka-ui-container
      ports:
         - '8090:8080'
      environment:
         - KAFKA_CLUSTERS_0_NAME=local
         - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka2:9092
         - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper2:2181
      depends_on:
         - kafka
         - zookeeper