version: '3'
services:
   # lazydocker:
   #    build:
   #       context: https://github.com/jesseduffield/lazydocker.git
   #       args:
   #          BASE_IMAGE_BUILDER: golang
   #          GOARCH: amd64
   #          GOARM:
   #    image: lazyteam/lazydocker
   #    container_name: lazydocker
   #    stdin_open: true
   #    tty: true
   #    volumes:
   #       - /var/run/docker.sock:/var/run/docker.sock
   #       - ./config:/.config/jesseduffield/lazydocker

   # postgresql:
   #    image: postgres:latest
   #    container_name: postgresql-container
   #    environment:
   #       POSTGRES_DB: my_database
   #       POSTGRES_USER: my_user
   #       POSTGRES_PASSWORD: 12345
   #    ports:
   #       - '5432:5432'
   #    volumes:
   #       - ./local_pgdata:/var/lib/postgresql/data

   # cassandra:
   #    image: cassandra:5.0
   #    container_name: cassandra-container
   #    ports:
   #       - '9042:9042'
   #    environment:
   #       - CASSANDRA_USER=admin
   #       - CASSANDRA_PASSWORD=admin
   #    volumes:
   #       - ./cassandra:/var/lib/cassandra
   #       - ./cassandra-logs:/var/log/cassandra

   redis:
      image: redis:latest
      container_name: redis-container
      ports:
         - '6379:6379'
      environment:
         - REDIS_LOG_LEVEL=notic

   nginx:
      image: nginx:latest
      container_name: nginx-container
      ports:
         - '80:80'
