version: '3'
services:
   # lazydocker:
   #    build:
   #       context: https://github.com/jesseduffield/lazydocker.git
   #       args:
   #          BASE_IMAGE_BUILDER: golang
   #          GOARCH: amd64
   #          GOARM:
   #    image: lazyteam/lazydocker
   #    container_name: lazydocker
   #    stdin_open: true
   #    tty: true
   #    volumes:
   #       - /var/run/docker.sock:/var/run/docker.sock
   #       - ./config:/.config/jesseduffield/lazydocker

   postgresql:
      image: postgres:latest
      container_name: postgresql-container
      environment:
         POSTGRES_DB: my_database
         POSTGRES_USER: my_user
         POSTGRES_PASSWORD: 12345
      # volumes:
      #    - ./local_pgdata:/var/lib/postgresql/data
      ports:
         - '5432:5432'
